### ISSUE TITLE
Service node uptime proof doesn't get sent for an hour after starting the node

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#259]
I restarted my active service node, which had about 45 minutes since the last network uptime proof.  No uptime proof got send out until the node had been running for a full hour after the restart.  The node's SN status reported:

```
    Last Uptime Proof Received: Not Received Yet
```

then finally, after an hour (and now 1h45m since the last uptime proof) the proof went out.

The problem, however, is that if the uptime proof doesn't go out for a full hour after restarting, I could have easily lost my SN status had I restarted a second time, e.g. with the following timing (all times relative to the last uptime proof on the network):

45m - restart 1
1h30m - restart 2
2h30m - uptime proof goes out

but the SN would have been deregistered after 2h5m.

Perhaps the timer could be be made more robust by shortening it to, say, 1 minute and have an added check to only send the proof if the last known proof for the SN is never (i.e. after a restart) or more than 59 minutes.

**Comment by traceds** [comment]
i'v got the same problem. Service node pubkey is:  d7d6592628876e2151ed6f845b48d37d2bd1ea38935ef88453166c86a90dbbe6
Coins are locked.    Is it possible to restart SN?

**Comment by Doy-lee** [comment]
For clarification, the rules as of Loki 'Magic Mani' since v0.3.0 beta, v1.0.0-rc.X and v1.0.X releases-

1. Service Nodes accept an up-time proof if they haven't seen one from you in the last 30 minutes.
2. Service Nodes can only begin submitting up-time proof starting 1 block after you register 
    ***and***
    Service Nodes can only begin submitting up-time proofs if it's in an idle state (i.e. the daemon is synced and serving the blockchain), every hour, starting immediately (i.e. right after you are in a synced state, you submit an up-time immediately and the 1hr intervals between uptime proofs begin).
3. When a Service Node receives an uptime proof over P2P, if I accept it (i.e. rule 1 is true), then relay it to my peers.
4. Service Nodes delete up time proofs once they are older than 2hrs and 5mins, at which point you are a candidate to be voted off.
5. Service Nodes cannot begin voting until the process (the daemon) has been running for more than 2 hours to ensure they have an opportunity to receive at least one up-time proof, depending on the timing overlap between your daemon starting up and other daemons transmitting up-times.

Every Service Node on the network has their own list of up-times, independent to the remainder of the network, so, the blockchain explorer is not a definitive source of the up-times of current nodes.

> The node's SN status reported:
Last Uptime Proof Received: Not Received Yet

If this is being reported by your own daemon, then, if other Service Nodes on the network already have a recent enough proof- then, you won't receive your proof back, leading to `Not Received Yet` when you check using `print_sn_status` (rule 3).

> The problem, however, is that if the uptime proof doesn't go out for a full hour after restarting

Up-time proofs are sent immediately on start-up if the preconditions in rule 2 are met.

The worst case in terms of broadcasting up-time timing overlaps that can occur is,
1. A service node broadcasts an up-time proof, where their last up-time proof is around ~29min 59s.
2. Every daemon rejects their up-time proof as their last up-time proof is still valid, by 1s.
3. The service node doesn't broadcast their ping for another hour at which point, their last up-time proof is now 1hr 29min 59s old.
4. Broadcast up-time, which is now valid - everyone agrees you are online, no risk of deregistration. (Note: At any point in time if you restart the daemon before the hourly interval, you immediately broadcast the up-time if rule 2 is met and this up-time would be accepted).

If the last up-time proof as reported by the explorer was 45 minutes ago, then a restart of the Service Node you would expect to submit an up-time proof and eventually hit the explorer and show up. The unknown here is, other Service Nodes do maintain their own list of up-times, which makes this harder to reason about, as to whether or not they decided to relay your up-time and make its way around the network. This is the only scenario I can think of that could have happened for your Service Node.

Since, every Service Node maintains their own list of up-times checking everyone for your own up-time, and them checking yours for their up-time proof, could become prohibitively expensive, compared to simply broadcasting their up-time proof. So to make the system more robust, this may not be the solution.

It may be in our best interest for now to increase the granularity of up-time broadcasting, to 30mins, as it's preferable that if we can help honest nodes stay alive at the cost of keeping dis-honest nodes alive for a little longer, that'd be better.

**Comment by Doy-lee** [comment]
> i'v got the same problem. Service node pubkey is: d7d6592628876e2151ed6f845b48d37d2bd1ea38935ef88453166c86a90dbbe6
> Coins are locked. Is it possible to restart SN?

Not possible to restart the Service Nodes or unlock the coins, they are locked on the blockchain for 30 days before returning to your account. In this case atleast 7 out of 10 nodes did not receive an up-time proof from your node and have voted the Service Node off the network.

**Comment by jagerman** [comment]
> Up-time proofs are sent immediately on start-up if the preconditions in rule 2 are met.

The preconditions were definitely satisfied for me; lokiblocks.com and my local uptime proof time were both 45 minutes when I restarted the node, and the SN has been active (and already received a couple rewards at that point) since the very beginning.

This is just a guess, but could there be a race condition between when the proof is sent out and peer connections being established -- i.e. it sent it to "all" peers, but there were no peer connections actually established yet?

**Comment by Doy-lee** [comment]
Addressed here. The problem is as @jagerman identified https://github.com/loki-project/loki/pull/262
