### ISSUE TITLE
Unable to start wallet-gui 2.0.1

### ISSUE THREAD

**Issue by Ossii** [loki-project/loki#364]
When trying to start loki-wallet-gui.exe I get thrown a few missing .dll files and then it exits.
The GUI never comes up, just the .dll errors then quit.

Windows 10 64bit - latest updates
loki-gui-windows-x64-2.0.1.zip

Errors, missing .dll files:
libgcc_s_seh-1.dll
libicuin61.dll
libicuuc61.dll

wallet dir is added to exclusion in windows defender.
starting lokid.exe works fine and it syncs.

**Comment by Ossii** [comment]
Ok, problem solved. The .dll files doesn't exist in the 2.0.1 .zip file, copied them over from 1.0.0 and all works ok now.
Please update 2.x .zip file to resolve this.

**Comment by jagerman** [comment]
I diffed the two zip contents (on a linux system, because Windows), and the following files were in the 1.0.0 windows zip but are missing from the 2.0.1 zip:

libgcc_s_seh-1.dll
libicudt61.dll
libicuin61.dll
libicuio61.dll
libicutu61.dll
libicuuc61.dll
start-low-graphics-mode.bat

**Comment by Doy-lee** [comment]
This was related to https://github.com/monero-project/monero-gui/issues/1559. The final bits of the build script did not complete properly meaning missing DLLs and scripts.

Qt build is still broken in general, needed the build machine to manually downgrade and get a copy of libicu*58.dlls for qmake to work.

Should be fixed in the updated binaries. Please reopen if there are any further issues. https://github.com/loki-project/loki-gui/releases

Thanks.
