### ISSUE TITLE
Relaxed Deregistration Rules

### ISSUE THREAD

**Issue by jpthor** [loki-project/loki#604]
## Abrupt De-registration Behaviour (prevent mass de-registration events)

**Issue**
A minor network issue can lead to a mass de-registration. See 12 May 2019, when almost 100 nodes where lost due to a network bug:

![image](https://user-images.githubusercontent.com/41815753/57577812-d35bd880-74c2-11e9-841f-ea58255abe8a.png)

Node operators that were on an older version and failed to upgrade in the two hour grace period (AFK, asleep, not online) suffered a mass de-registration event. 

**Current Behaviour**
The service nodes follow the current cadence for a deregistration:

Time T: Uptime Proof
T + 1 hour: Enter grace period. 
T + 2 hours: Deregistration. 

**Improved Behaviour**
The suggested behaviour is to add a penalty period after the grace period before being removed from the network:

Time T: Uptime Proof
T + 1 hour: Enter grace period. 
 -> If corrected: resume Service Node cycle. 

T + 2 hours: Enter penalty period. 
 -> Reset node to bottom of reward list (in effect removing their upcoming reward)
 -> If corrected: resume Service Node cycle. 

T + 24 hours: Exit penalty period. 
 -> Remove node from Service Node list (deregistration) and begin 30 day lock cycle (punishment) 

**Reasoning**
 Nodes typically go offline due bugs, network partitions, running older software and server problems - very rarely because they were being malicious. A hour's notice (from the start of the grace period) is not enough time (as evident by the events of 12 May 2019) and the author's own experience, to debug the node and update software (which may include a full chain re-validation).

Since the punishment period of 30 days is significant, the penalty period should be extended to at least 1 day (24 hours) allowing node operators globally a full day's cycle to debug their node. 

A penalty period (no reward) will encourage node operators to restore their node promptly.

**Comment by SomethingGettingWrong** [comment]
Under the current rules when a node is deregistered it is ignored for 30 days as well as it isn't allowed to serve a function for Loki net correct? 

This is a much better approach except between T+2 and T+24 the service node also needs to be ignored as if it was deregistered.  You do not want it to continue to serve a function on the wrong fork while its being corrected.  Maybe im misunderstanding and it already would do this. 

But this is an excellent idea until the network gets more mature.

**Comment by jagerman** [comment]
The issue here (and the reason for the is that there wouldn't really be much of a penalty for being sloppy with your service node.  If it goes down 2-3 times per month, well, no big deal, I will just forego some penalties.

However there may be some possibility of a grace period by using the amount of time the SN has stayed up (I'm not 100% sure we want it, but I'm throwing this out for thought).  Here are a couple ideas:

1. When you first fail an uptime proof (i.e. pass the 2-hour threshold), and have been deemed a "reliable" service node, you would get a "deactivation" which would remove you from the service node list both for rewards and for lokinet duties.  You would remain in the pool of service nodes to check for uptime proofs, however.

2. If you fail an uptime proof check and are deemed unreliable, you get a deregistration.

3. If you are currently registered but deactivated and start passing the uptime proof again, the quorum submits a reactivation transaction.  This puts you at the bottom of the reward list.

4. If you are currently registered but deactivated and cross another threshold (e.g. 12 hours or 24 hours?) you get deregistered.

"reliable" here would be a measurement based on how long you have been active: so, for example, we might consider a service node that has been online for at least 15 days and has had no deactivation in the last 30 days as reliable.

Or alternatively we could build a sort of reputation: a new service node registration has a score that starts at 1, gains 1 for every 30 days it remains registered, and loses 1 every time it gets deactivated.  (This would also require some amendment to rule 4 - if you cross the "bad" threshold and still have points left you would get a renewed deactivation that would remove another point, and buy you another 12 or 24 hours (or whatever)).

One potential interesting effect of this alternative is that it provides an incentive for infinite staked service nodes to stay registered.  I think there are a fair number of SNs currently that go through constant unstake–restake cycles to reduce the staking amount.

**Comment by KeeJef** [comment]
I think we should be reluctant to build a more complex system based on uptime proofs since they will eventually be disabled or minimized to make way for more complex tests that better reflect the overall performance of a node.

I think the most sensible thing to do would be to create a reputation system where proof of your previous performance can be used to give you an additional buffer from real de-registrations. This way when a quorum is processing a de-registration they have the choice between a nuclear option (Dereg) or a less severe option (Decommissioning) which pushes the node to the bottom of the rewards list until it provides a uptime proof to the next testing quorum, and disables its contact in the DHT so it cant route in Lokinet or store messages.

If we were to do this with uptime proofs i would like to see a system where 

After 15 Days each 24 Hours you are online awards you one hour of decommission time (up to a cap of 24 hours), if you have not submitted an uptime proof in the last 2 hours a quorum views your total uptime, if you have any decommissioning points then the quorum processes a decommission.

Once decommissioned your decommission time starts ticking down, if you do not start submitting uptime proofs before the next Quorum tests you and your decommission time has run out then the quorum may process a de-registration.

**Comment by jagerman** [comment]
> Once decommissioned your decommission time starts ticking down, if you do not start submitting uptime proofs before the next Quorum tests you and your decommission time has run out then the quorum may process a de-registration.

I think we'd need quorums to keep testing you, and then eventually end your purgatory with either a "recommissioning" transaction to reinstate you to the reward list or a deregistration when you run out of time without reappearing.

**Comment by KeeJef** [comment]
the previous Quorum could place a decommission transaction onchain, once the decommission transaction appears on chain then the following quorums could be required to test your node. i dont think you need a recommission transaction, since if you are still operating after your decommission time has run out its implicit that you have started sending uptime proofs again otherwise you would be deregistered from the network

**Comment by jagerman** [comment]
> i dont think you need a recommission transaction, since ...

The issue is that we need a definitive network-level point at which the node becomes active again.  I suppose you *could* just do something like +60 blocks after the last decommission, but then you need a continual series of decommissions (i.e. every 59 blocks or less) to keep it from being used on the network.

**Comment by KeeJef** [comment]
Instead of giving 1 hour of decommission per 24 hours of uptime, we could give 30 blocks of decommission time for each 720 blocks you are alive? now we shoulden't have to deal with time at all

**Comment by jagerman** [comment]
> we could give 30 blocks of decommission time for each 720 blocks you are alive?

Wouldn't that mean that nodes that have been alive for longer go without a reward for longer when they go down?

I don't think supporting both `decommission -> recommission` or `decommission -> deregister transactions` are a technical problem, and they keep the current SN state crystal clear (and a bit simpler to calculate).  It also has the advantage that if you come back sooner, you go back onto the reward list sooner.

**Comment by KeeJef** [comment]
> Wouldn't that mean that nodes that have been alive for longer go without a reward for longer when they go down?

Yes, but it would be capped at 24 hours and its likely to be a very rare event for a honestly operating SN.

> I don't think supporting both decommission -> recommission or decommission -> deregister transactions are a technical problem, and they keep the current SN state crystal clear (and a bit simpler to calculate). It also has the advantage that if you come back sooner, you go back onto the reward list sooner.

trying to avoid an additional onchain cost/bloat is the main driver for not wanting Decommission + recommission + deregister txes.

**Comment by Fez29** [comment]
Just my input.

I personally like both arguments but do think that if a service node comes back online sooner it should be added back onto the reward list sooner, I guess the question to be asked would be what would the additional cost/bloat caused by the Decommission + recommission + deregister txes actually be?

Also which option would be better going forward once more complex tests are implemented on service and would the additional cost be substantially more in regards to  Decommission + recommission + deregister txes.

**Comment by jagerman** [comment]
@Fez29 - dereg transactions are very small (less than 1/3 of the size of the smallest TX you can send funds in).  I'm actually slimming them down slightly more for the next fork.


As to the main issue, this was suggested just now on Telegram, which I found intriguing:
[William E. Coyote, [15.06.19 23:55]
[In reply to Jason]
Pay to play? First 8-24  hours no problem. After that, pay Loki to burn address at 1/2 or so rewards you would receive to reregister node early.

William E. Coyote, [15.06.19 23:56]
Network stays strong, bad operators get penalized.

William E. Coyote, [15.06.19 23:58]
Continual poor performance would get expensive.


I kind of like that idea, but perhaps it should still have a minimum of a week or something (so in other words you can "buy off" several days of penalty time).

**Comment by KeeJef** [comment]
I think that would add a fair bit of complexity to the current scheme, although it would be another good way to burn currency

**Comment by Fez29** [comment]
So the bloat technically would be pretty negligible in real terms as this should not be something that is occurring daily and would not be large volumes of nodes either way. (hopefully)

The payoff option is a great idea in my view as it allows for a once off occurrence to be catered for but as mentioned would become expensive if is a regular occurrence, Also i do think a minimum would be a good "control" to have in place.

**Comment by CryptoFirefly** [comment]
My thoughts on improving the model 

Objectives achieved by this
a. Support the SN community to have a life, be able to monitor the SNs actively but also not be penalized for 30 days, just incase the issue happens at their night time.
b. Avoid Mass DeRegs reducing our overall active SN count
c. Not over complicate the process. It works well not and with the soon to hit 1000 SNs active milestone the rewards are going to drop massively and credited less often than once a day. Too complex a process will drive away the Operators. 

Suggested Approach that keeps the Core process same but solves the current 2 hour only window issue for majority of the long term Loki operators. 

**1. First 30 days of lock-in.** _(Mostly as-is with some leniency before 30-day lock)_
a. The Operators get a 2 hours window to get back online. If it missed the 2 hours uptime proof they are dropped off the rewards Queue and have upto 12 hrs since last uptime proof to get back online. (i.e. 10 more hrs after being removed the rewards Queue)

1.b. The Operators that get back online within the 12 hrs window, rejoin at the bottom of the rewards.
If they are not back online their Loki (+contributors) is lock for 30-days. 

Anytime the SN crosses the 2hrs uptime proof mark, its 30 day lock-in to gain next level is reset to 0.


**2. Once the SN crosses 30 days without 2+ hrs of downtime, it gets additional benefits and can be termed Premium Node**

a. SN operators will have upto 6 hrs to restore the SN, while still being within the rewards Queue. 

b. Once the 6 hrs is past, the SN is removed from the rewards Queue and Operators have upto 12 hrs from last uptime proof, to rejoin the network. If the SN rejoins the network within these 12 hrs, its Premium Node status is retained and it rejoins the rewards queue at the bottom. 

c. Being a Premium Node, it gets additional 12 hrs, so has upto 24 hrs since last uptime proof to restore the node. If restored within 24 hrs (i.e. between 12+ to upto 24 hrs) it rejoins the rewards Queue at the bottom and has this additional fail-safe benefit for serving well for 30+ days. But would loose its Premium Node status, which it can regain by being online without a glitch for next 30 days. 

d. If the SN is not brought back-up within 24 hrs, the Loki will be locked for 30-days. 
 

Planned unlock should stay at 15 days, which is good to keep Loki locked up and avoid quick dump on price jumps. Suggest we keep it simple vs having a fee to unlock quicker.

**Comment by KeeJef** [comment]
Relaxed Deregistration was implemented in 4.0.0 Hefty Hiemdall you can read the parapaters and design we used here
