### ISSUE TITLE
Wallet synchronisation issue

### ISSUE THREAD

**Issue by Phillyblunt** [loki-project/loki#67]
I tried opening as administrator but still can't sync. It just instructs me to "check your wallet and daemon log for errors" any tips on this?

**Comment by Doy-lee** [comment]
Could you provide some more information? Operating system? Daemon logs and output from launching the daemon?

The current issues at the moment include anti-virus software flagging files, or firewalls blocking ports because it is mining software, particularly on Windows. Similarly, blockchain could be corrupted and needed to be deleted etc.

**Comment by Phillyblunt** [comment]
hi Doyle,

thank you for your response. since my query I have deleted my wallet a
number of times and eventually was able to download a version that synced
up just fine.

Thanks again

Philip

**Comment by shrewdacumen** [comment]
I have the same problem too.  On my MacBook Pro (High Sierra) Loki-wallet its daemon keeps loading blocks during more than 10 hours which never ends.
<img width="1424" alt="screen shot 2018-09-11 at 11 41 27 am" src="https://user-images.githubusercontent.com/684684/45334868-ab287c80-b5b7-11e8-9cac-40bbafa95c12.png">
