### ISSUE TITLE
Service Node Registration Fails with no errors and funds returned unlocked

### ISSUE THREAD

**Issue by lrosa007** [loki-project/loki#775]
This has happened with 3 nodes in a row now, full tear down every time.

1. The register command is run from the Operators' wallet
2. [tx](https://lokiblocks.com/tx/0591f4b121ac8fef9a9b4caef9f3badd3b1d57488e7fac40df70e2b6a97b0d8e) goes out just fine
3. funds seem to be locked/withdrawn
4. funds return unlocked to wallet and node never registers

* This is being set up as a Reserved Pool with 3 additional contributors
* Everyone has the proper amount of funds unlocked
* We have successfully put up 2 other Reserved Pools this past month by following the [service node full guide](https://lokidocs.com/ServiceNodes/SNFullGuide/).

transaction link:
https://lokiblocks.com/tx/0591f4b121ac8fef9a9b4caef9f3badd3b1d57488e7fac40df70e2b6a97b0d8e

**To Reproduce**

Follow the [service node full guide](https://lokidocs.com/ServiceNodes/SNFullGuide/)

**Expected behavior**

After tx is confirmed the node should show up [here](https://lokiblocks.com/search_service_node?value=1f6d6840ad768c2ca4da007ba6b88834567a94b2844860afb642062163dfbb28)

**Current Behaviour**

node never registers

**Screenshots or Logs**

Logs have messages related to quorum state not being able to be cached

`[P2P4]  ERROR   quorum_cop      src/cryptonote_core/service_node_quorum_cop.cpp:446     Quorum state for height: 326121 was not cached in daemon!`

**Additional Information:**
- Ubuntu 16.04
- Digital Ocean
- Remote node
- Hefty Heimdal 3.0.4
- Loki Launcher 1.0.0

**Comment by jagerman** [comment]
It's very likely that the issue is caused by the third and fourth amounts being exactly equal.  There is a little bit of rounding that happens in a stake and if it goes the wrong way, you can end up with a registration that isn't valid because it is slightly too small in the very last digit of the reserved amount.  We have some workarounds for this in place, but it appears you ran into another edge case.

(Ideally for 5.0 I'd like to replace the staking code with a simpler version that records all the stakes as fixed amounts determined at registration, rather than percentage-based amounts that get interpreted when the block gets mined, but that's not the case currently).

As a workaround for this specific situation try *slightly* increasing (even an adjustment of 0.0001 LOKI will be enough) the stake of contribution 3 and slightly decreasing the stake of contribution 4.

**Comment by Doy-lee** [comment]
I've done some debugging with the transaction in question and have found that it's failing a signature check using the given service node public key.

If you're not too attached to your service node key, you may delete the key file and let the daemon generate a new one when you start it up and give that a shot incase something funky is going on with the current key. The key file is located at ~/.loki/key

**Comment by lrosa007** [comment]
@jagerman @Doy-lee I'll report back ASAP with findings. Thank you.

**Comment by lrosa007** [comment]
@jagerman That was exactly it, thank you
