### ISSUE TITLE
export_transfers in broken 

### ISSUE THREAD

**Issue by tokerato** [loki-project/loki#821]
Error when doing either "export_transfers" or "export_transfers in" on Loki version 4.0.5: 

Error: Warning: Unhandled pay type, this is most likely a developer error, please report it to the Loki developers.

This address hasn't been earning staking rewards for some time and previous attempts to export transfers on earlier versions were working without issue.

Other wallet address exports went through without issue on the same machine/loki version. Issue specific to this address.

**Comment by Doy-lee** [comment]
Are the previous said version that this was tested on v2, or v3 releases? If this wallet has been lying dormant since and you attempt to `export_transfers` on a version after we introduced categorising transactions then you will get this error.

I believe the wallet cache for this file has some changes from some prior version that is not binary compatible with the new version. If you `rescan_bc hard` or delete your wallet file (not the keys) you should not have this problem.

Other wallets would not have this problem if they were generated on software after this change was added. I don't recall but v2.X.Y or v3.X.Y.

**Comment by tokerato** [comment]
rescan_bc hard resolved the issue thanks
