### ISSUE TITLE
goods not in wallet

### ISSUE THREAD

**Issue by puka89** [loki-project/loki#92]
I started the wallet, went to receive , copied the wallet address in the miner and 3 days after the transaction, still nothing, double and triple checked the address, i can't see what's wrong...

https://i.imgur.com/s1fjgup.png

**Comment by Doy-lee** [comment]
Given the screenshot, your wallet is style synchronising to network and subsequently loading blocks in the chain with transactions that have occurred since the start of the network. Your transaction is most likely in one of the latest blocks on the chain so your wallet must be synced for it to show up (assuming the address the transfer was sent to is correct).

You can connect to a remote node which has the chain pre-synced, for example doopool.xyz at P\port number: 22020. You can connect to a remote node in the settings of the GUI.

**Comment by Doy-lee** [comment]
Closed because of no further leads and issue age.
